-- Your SQL goes here
CREATE TABLE SC_TB(
    TB_ID INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCR VARCHAR
(255) NOT NULL,
    STATUS CHAR
(1) NOT NULL DEFAULT 'Y',
    CREATED_DATE DATETIME NOT NULL,
    INDEX IDX_1
(DESCR)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SC_TDB(
    TDB_ID INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TB_ID INT
(11) NOT NULL,
    DESCR VARCHAR
(255) NOT NULL,
    STATUS CHAR
(1) NOT NULL DEFAULT 'Y',
    CREATED_DATE DATETIME NOT NULL,
    INDEX IDX_1
(DESCR),
    KEY SC_TB_1
(TB_ID),
    CONSTRAINT SC_TDBFK_1 FOREIGN KEY
(TB_ID) REFERENCES SC_TB
(TB_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE SC_TD(
    TD_ID INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TB_ID INT
(11) NOT NULL,
    DESCR VARCHAR
(255) NOT NULL,
    STATUS CHAR
(1) NOT NULL DEFAULT 'Y',
    CREATED_DATE DATETIME NOT NULL,
    INDEX IDX_1
(DESCR),
    KEY SC_TD_1
(TB_ID),
    CONSTRAINT SC_TDFK_1 FOREIGN KEY
(TB_ID) REFERENCES SC_TB
(TB_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE SC_ELC
(
    EC_ID INT(11)
    AUTO_INCREMENT NOT NULL,
    TB_ID INT
    (11) NOT NULL,
    TDB_ID INT
    (11) NOT NULL,
    DESCR VARCHAR
    (255) NOT NULL,
    STATUS CHAR
    (1) NOT NULL DEFAULT 'Y',
    CREATED_DATE DATETIME NOT NULL,
    PRIMARY KEY
    (EC_ID, TB_ID, TDB_ID),
    INDEX IDX_1
    (DESCR),
    KEY SC_ELC_1
    (TB_ID),
    KEY SC_ELC_2
    (TDB_ID),
    CONSTRAINT SC_ECFK_1 FOREIGN KEY
    (TB_ID) REFERENCES SC_TB
    (TB_ID),
    CONSTRAINT SC_ECFK_2 FOREIGN KEY
    (TDB_ID) REFERENCES SC_TDB
    (TDB_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;