[tasks.watch]
script = [
    "systemfd --no-pid -s http::8080 -- cargo watch -x run"
]

[tasks.db-make]
script = [
    "diesel migration generate ${@}"
]

[tasks.db-up]
script = [
    "diesel migration run"
]

[tasks.db-down]
script = [
    "diesel migration revert"
]

[tasks.db-redo]
script = [
    "diesel migration redo"
]

[tasks.db-reset]
script = [
    "diesel database reset"
]