-- Your SQL goes here
Create TABLE SC_APP_ACCESS_LOG(
    ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ID INT
(11) NOT NULL,
    NIK VARCHAR
(100) NOT NULL,
    USER_LOGIN VARCHAR
(100) NOT NULL,
    EMPLOYEE_NAME VARCHAR
(255) NOT NULL
    APPLICATION_ID VARCHAR
(100) NOT NULL,
    APPLICATION_NAME VARCHAR
(100) NOT NULL,
    VERSION_CODE VARCHAR
(100) NOT NULL,
    VERSION_NAME VARCHAR
(100) NOT NULL,
    OS VARCHAR
(100) NOT NULL,
    DEVICES VARCHAR
(100) NOT NULL,
    IMEI VARCHAR
(100) NOT NULL,
    IP_ADDRESS VARCHAR
(100) NOT NULL,
    DB_VERSION VARCHAR
(100) NOT NULL,
    DB_NAME VARCHAR
(100) NOT NULL,
    LATLNG VARCHAR
(100) NOT NULL,
    TIME_LNG VARCHAR
(100) NOT NULL,
    DATA TEXT NOT NULL,
    PROCESS VARCHAR
(100) NOT NULL,
CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
INDEX IDX_1
(EMPLOYEE_ID),
INDEX IDX_2
(NIK),
INDEX IDX_3
(USER_LOGIN),
INDEX IDX_4
(PROCESS)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SC_TOKEN(
ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_ID INT
(20) NOT NULL,
TOKEN TEXT NOT NULL,
LAST_LOGIN DATETIME,
LAST_LOGOUT DATETIME,
INDEX IDX_1
(EMPLOYEE_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;