-- Your SQL goes here

CREATE TABLE SC_MATRIX(
    MAT_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PROD_SLS INT
(11) NOT NULL,
    BF_PROD_SLS INT
(11) NOT NULL,
    ADDON_SLS CHAR
(1) NULL,
    MIN_BF_ADDON_SLS INT
(11) NULL,
    SCORE INT
(11) NOT NULL,
    REGION VARCHAR
(255) NOT NULL,
    PROD_TS INT
(11) NOT NULL,
    BF_PROD_TS INT
(11) NOT NULL,
    ADDON_TS CHAR
(1) NULL,
    BF_ADDON_TS INT
(11) NULL,
 STATUS CHAR
(1) DEFAULT 'Y',
    CREATED_DATE DATETIME,
    INDEX IDX_1
(PROD_SLS),
    INDEX IDX_2
(PROD_TS),
    INDEX IDX_3
(REGION),
    INDEX IDX_4
(SCORE),
    CONSTRAINT SC_MATRX UNIQUE
(PROD_SLS, BF_PROD_SLS, PROD_TS, BF_PROD_TS, REGION, SCORE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SC_MAPPING_PRODUCT(
 MAP_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
 PRODUCT_ID INT
(11) NOT NULL,
 PRODUCT_NAME VARCHAR
(255) NOT NULL,
 BILL_FREQ INT
(11) NOT NULL,
 PROMO_ID INT
(11) NOT NULL,
 PROMO_CODE VARCHAR
(100) NOT NULL,
 PROMO_DESCR TEXT NOT NULL,
 STATUS CHAR
(1) DEFAULT 'Y',
 CREATED_DATE DATETIME,
 INDEX IDX_1
(PRODUCT_ID),
 INDEX IDX_2
(PROMO_ID),
 INDEX IDX_3
(PROMO_CODE),
INDEX IDX_4
(PRODUCT_NAME),
 CONSTRAINT SC_MAP_PROD UNIQUE
(PRODUCT_ID, PROMO_ID, PROMO_CODE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SC_SCORE(
    SEC_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TB_ID INT
(11) NOT NULL,
    TDB_ID INT
(11) NOT NULL,
    TD_ID INT
(11)  NULL,
    EC_ID INT
(11) NOT NULL,
    SCORE INT
(11) NOT NULL,
    SEC VARCHAR
(255) NOT NULL,
    STATUS CHAR
(1) DEFAULT 'Y',
    CREATED_DATE DATETIME,
        KEY SC_SCO_1
(TB_ID),
        KEY SC_SCO_2
(TDB_ID),
        KEY SC_SCO_3
(TD_ID),
        KEY SC_SCO_4
(EC_ID),
        CONSTRAINT SC_SCOFK_1 FOREIGN KEY
(TB_ID) REFERENCES SC_TB
(TB_ID),
        CONSTRAINT SC_SCOFK_2 FOREIGN KEY
(TDB_ID) REFERENCES SC_TDB
(TDB_ID),
        CONSTRAINT SC_SCOFK_3 FOREIGN KEY
(TD_ID) REFERENCES SC_TD
(TD_ID),
        CONSTRAINT SC_SCOFK_4 FOREIGN KEY
(EC_ID) REFERENCES SC_ELC
(EC_ID),
    INDEX IDX_1
(SCORE),
    INDEX IDX_2
(SEC)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;
